backup scripts fixed

diff --git a/cookbooks/algorythm/templates/default/backup.sh.erb b/cookbooks/algorythm/templates/default/backup.sh.erb
--- a/cookbooks/algorythm/templates/default/backup.sh.erb
+++ b/cookbooks/algorythm/templates/default/backup.sh.erb
@@ -39,9 +39,9 @@ case "$ACTION" in
 	;;
 esac
 
-BACKUP_INSTALL_DIR=$(dirname $(readlink -f "$SCRIPT_NAME"))
-LOG_DIR="$BACKUP_INSTALL_DIR/log"
-PATH="$PATH:$BACKUP_INSTALL_DIR/bin"
+INSTALL_DIR=$(dirname $(readlink -f "$SCRIPT_NAME"))
+LOG_DIR="$INSTALL_DIR/log"
+PATH="$PATH:$INSTALL_DIR/bin"
 BACKUP_ID="backup-$BACKUP_DATE"
 LOG_FILE="$LOG_DIR/$BACKUP_ID.log"
 TMP_DIR="/tmp/$BACKUP_ID"
@@ -71,15 +71,13 @@ function runBackupTask {
 	SCRIPT_FILE="$1"
 	BACKUP_TYPE=$(toBackupType $SCRIPT_FILE)
 	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
-
-	echo "* $ACTION_LABEL $BACKUP_TYPE ..."
 	
 	BACKUP_ARCHIVE="$BACKUP_DIR/$BACKUP_TASK_ID.tar.bz2"
 	CUR_TMP_DIR="$TMP_DIR/$BACKUP_TASK_ID"
 
 	if [ $ACTION = 'dump' ]; then
 		if [ -f $BACKUP_ARCHIVE ]; then
-			echo "  ... failed: $BACKUP_ARCHIVE already exists" 2>&1
+			echo "-> failed: $BACKUP_ARCHIVE already exists"
 			SCRIPT_ERROR=true
 			return 1
 		fi
@@ -88,7 +86,7 @@ function runBackupTask {
 		chmod 777 $CUR_TMP_DIR
 	else
 		if [ ! -f $BACKUP_ARCHIVE ]; then
-			echo "  ... failed: $BACKUP_ARCHIVE does not exist" 2>&1
+			echo "-> failed: $BACKUP_ARCHIVE does not exist"
 			SCRIPT_ERROR=true
 			return 1
 		fi
@@ -98,58 +96,60 @@ function runBackupTask {
 		STATUS=$?
 
 		if [ $STATUS != '0' ]; then
-			echo "  ... failed: Couldn't extract $BACKUP_ARCHIVE in $TMP_DIR" 2>&1
+			echo "-> failed: Couldn't extract $BACKUP_ARCHIVE in $TMP_DIR"
 			SCRIPT_ERROR=true
 			return 1
 		fi
 	fi
 
-	sh "$BACKUP_INSTALL_DIR/tasks/$SCRIPT_FILE" $ACTION $CUR_TMP_DIR
-	STATUS=$?
+	sh "$INSTALL_DIR/tasks/$SCRIPT_FILE" $ACTION $CUR_TMP_DIR
 
-	if [ $STATUS = '0' ]; then
+	if [ $? = '0' ]; then
 		if [ $ACTION = 'dump' ]; then
 			cd $TMP_DIR
 			tar cjf $BACKUP_ARCHIVE $BACKUP_TASK_ID
-			STATUS=$?
 
-			if [ $STATUS = '0' ]; then
+			if [ $? = '0' ]; then
 				chmod 600 $BACKUP_ARCHIVE
 			else
-				echo "  ... failed: Couldn't compress and save backup to $BACKUP_ARCHIVE" 2>&1
+				echo "-> failed: Couldn't compress and save backup to $BACKUP_ARCHIVE"
 				SCRIPT_ERROR=true
 				return 1
 			fi
 		fi
 
-		echo "  ... finished"
+		echo "-> done"
 		return 0
 	else
-		echo "  ... $scriptName $ACTION failed" 2>&1
+		echo "-> failed"
 		SCRIPT_ERROR=true
 		return 1
 	fi
 }
 
-echo "$ACTION_LABEL $BACKUP_DATE in $BACKUP_DIR"
+echo "$ACTION_LABEL $BACKUP_DATE in $BACKUP_DIR:"
 
-for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
+for SCRIPT_FILE in $(ls "$INSTALL_DIR/tasks" | grep -P "\.sh"); do
 	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
+	BACKUP_TYPE=$(toBackupType $SCRIPT_FILE)
+	echo "  - $BACKUP_TYPE"
+
 	runBackupTask "$SCRIPT_FILE" >> "$LOG_DIR/$BACKUP_TASK_ID.log" &
+
 	rm -rf $TMP_DIR/$BACKUP_TASK_ID
 done
 wait
 
-for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
+for SCRIPT_FILE in $(ls "$INSTALL_DIR/tasks" | grep -P "\.sh"); do
 	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
 	echo "### $ACTION_LABEL $BACKUP_TYPE ###" >> "$LOG_FILE"
 	cat "$LOG_DIR/$BACKUP_TASK_ID.log"    >> "$LOG_FILE"
 	rm -rf "$LOG_DIR/$BACKUP_TASK_ID.log"
 
 	if $SCRIPT_ERROR; then
-		echo "Finished with error(s)" >> "$LOG_FILE"
+		echo "=> Finished with error(s)" >> "$LOG_FILE"
 	else
-		echo "Finished successfully"  >> "$LOG_FILE"
+		echo "=> Finished successfully"  >> "$LOG_FILE"
 	fi
 done
 
@@ -160,4 +160,5 @@ if $SCRIPT_ERROR; then
 	exit 3
 else
 	echo "Finished successfully"
+	echo "Run 'backup restore $BACKUP_DATE' to restore your backup"
 fi
