backup scripts fixed

diff --git a/cookbooks/algorythm/templates/default/backup.sh.erb b/cookbooks/algorythm/templates/default/backup.sh.erb
--- a/cookbooks/algorythm/templates/default/backup.sh.erb
+++ b/cookbooks/algorythm/templates/default/backup.sh.erb
@@ -1,8 +1,8 @@
 #!/bin/bash
-###################################
+#####################################
 # Usage: backup {dump|restore DATE} #
-# Must be run as root             #
-###################################
+# Must be run as root               #
+#####################################
 
 if [ $(id -u) != '0' ]; then
 	echo 'You need root privileges to run this script' 2>&1
@@ -27,34 +27,55 @@ case "$ACTION" in
 		BACKUP_DATE=$(date +'%y-%m-%d_%H-%M')
 	;;
 	restore)
-		if [[ -z "$2" ]]; then
-			showUsageAndExit
-		fi
-
 		ACTION_LABEL="Restoring"
 		BACKUP_DATE="$2"
+
+		if [ -z "$BACKUP_DATE" ]; then
+			showUsageAndExit
+		fi
 	;;
 	*)
 		showUsageAndExit
 	;;
 esac
 
-TIMESTAMP=$(date +%s)
-BACKUP_INSTALL_DIR=$(dirname $(readlink -f "$0"))
+BACKUP_INSTALL_DIR=$(dirname $(readlink -f "$SCRIPT_NAME"))
 LOG_DIR="$BACKUP_INSTALL_DIR/log"
 PATH="$PATH:$BACKUP_INSTALL_DIR/bin"
-TMP_DIR="/tmp/backup-$BACKUP_DATE"
+BACKUP_ID="backup-$BACKUP_DATE"
+LOG_FILE="$LOG_DIR/$BACKUP_ID.log"
+TMP_DIR="/tmp/$BACKUP_ID"
 SCRIPT_ERROR=false
+
+if [ -d $TMP_DIR ]; then
+	echo "Temp directory $TMP_DIR is in use" 2>&1
+	exit 4
+fi
+
+mkdir $TMP_DIR
+mkdir -p $BACKUP_DIR
+
+function toBackupType {
+	SCRIPT_FILE=$1
+	BACKUP_TYPE=${SCRIPT_FILE%.sh}
+	echo ${BACKUP_TYPE#backup-}
+}
+
+function toBackupTaskId {
+	SCRIPT_FILE=$1
+	BACKUP_TYPE=$(toBackupType $SCRIPT_FILE)
+	echo "$BACKUP_TYPE-$BACKUP_DATE"
+}
 
 function runBackupTask {
 	SCRIPT_FILE="$1"
-	TASK_NAME="$2"
+	BACKUP_TYPE=$(toBackupType $SCRIPT_FILE)
+	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
 
-	echo "* $ACTION_LABEL $TASK_NAME ..."
-
-	BACKUP_ID="$TASK_NAME-$BACKUP_DATE"
-	BACKUP_ARCHIVE="$BACKUP_DIR/$BACKUP_ID.tar.bz2"
-	CUR_TMP_DIR="$TMP_DIR/$BACKUP_ID"
+	echo "* $ACTION_LABEL $BACKUP_TYPE ..."
+	
+	BACKUP_ARCHIVE="$BACKUP_DIR/$BACKUP_TASK_ID.tar.bz2"
+	CUR_TMP_DIR="$TMP_DIR/$BACKUP_TASK_ID"
 
 	if [ $ACTION = 'dump' ]; then
 		if [ -f $BACKUP_ARCHIVE ]; then
@@ -89,7 +110,7 @@ function runBackupTask {
 	if [ $STATUS = '0' ]; then
 		if [ $ACTION = 'dump' ]; then
 			cd $TMP_DIR
-			tar cjf $BACKUP_ARCHIVE $BACKUP_ID
+			tar cjf $BACKUP_ARCHIVE $BACKUP_TASK_ID
 			STATUS=$?
 
 			if [ $STATUS = '0' ]; then
@@ -110,24 +131,32 @@ function runBackupTask {
 	fi
 }
 
-echo "$ACTION_LABEL $BACKUP_DIR/*/$BACKUP_ID"
-
-mkdir -p $BACKUP_DIR
-mkdir $TMP_DIR
+echo "$ACTION_LABEL $BACKUP_DATE in $BACKUP_DIR"
 
 for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
-	TASK_NAME=${SCRIPT_FILE#backup-}
-	TASK_NAME=${TASK_NAME%.sh}
-	LOG_NAME=
-	runBackupTask "$SCRIPT_FILE" "$TASK_NAME" >>  &
-	rm -rf $TMP_DIR/$BACKUP_ID
+	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
+	runBackupTask "$SCRIPT_FILE" >> "$LOG_DIR/$BACKUP_TASK_ID.log" &
+	rm -rf $TMP_DIR/$BACKUP_TASK_ID
 done
 wait
+
+for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
+	BACKUP_TASK_ID=$(toBackupTaskId $SCRIPT_FILE)
+	echo "### $ACTION_LABEL $BACKUP_TYPE ###" >> "$LOG_FILE"
+	cat "$LOG_DIR/$BACKUP_TASK_ID.log"    >> "$LOG_FILE"
+	rm -rf "$LOG_DIR/$BACKUP_TASK_ID.log"
+
+	if $SCRIPT_ERROR; then
+		echo "Finished with error(s)" >> "$LOG_FILE"
+	else
+		echo "Finished successfully"  >> "$LOG_FILE"
+	fi
+done
 
 rm -rf $TMP_DIR
 
 if $SCRIPT_ERROR; then
-	echo "Finished with error(s)"
+	echo "Finished with error(s) (see log file $LOG_FILE)"
 	exit 3
 else
 	echo "Finished successfully"
