backup scripts fixed

diff --git a/cookbooks/algorythm/templates/default/backup.sh.erb b/cookbooks/algorythm/templates/default/backup.sh.erb
--- a/cookbooks/algorythm/templates/default/backup.sh.erb
+++ b/cookbooks/algorythm/templates/default/backup.sh.erb
@@ -9,6 +9,10 @@ if [ $(id -u) != '0' ]; then
 	exit 1
 fi
 
+if [ -z "$BACKUP_DIR" ]; then
+	BACKUP_DIR='<%=@backupDir%>'
+fi
+
 SCRIPT_NAME="$0"
 ACTION="$1"
 
@@ -36,18 +40,12 @@ case "$ACTION" in
 esac
 
 BACKUP_INSTALL_DIR=$(dirname $(readlink -f "$0"))
+PATH="$PATH:$BACKUP_INSTALL_DIR/bin"
 TMP_DIR="/tmp/$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32)"
-scriptError=0
+SCRIPT_ERROR=0
 
-if [ -z "$BACKUP_DIR" ]; then
-	BACKUP_DIR='<%=@backupDir%>'
-fi
-
-echo "$ACTION_LABEL $BACKUP_DIR/*/$BACKUP_ID"
-
-mkdir $TMP_DIR
-
-for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
+function runBackupTask {
+	SCRIPT_FILE="$1"
 	TASK_NAME=${SCRIPT_FILE#backup-}
 	TASK_NAME=${TASK_NAME%.sh}
 
@@ -62,34 +60,65 @@ for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
 		mkdir $CUR_TMP_DIR
 		chmod 777 $CUR_TMP_DIR
 	else
+		if [ ! -f $BACKUP_ARCHIVE ]; then
+			echo "  ... failed: $BACKUP_ARCHIVE does not exist" 2>&1
+			return 1
+		fi
+
 		cd $TMP_DIR
-		tar xjvf $BACKUP_ARCHIVE
+		tar xjf $BACKUP_ARCHIVE
+		STATUS=$?
+
+		if [ $STATUS != '0' ]; then
+			echo "  ... failed: Couldn't extract $BACKUP_ARCHIVE in $TMP_DIR" 2>&1
+			return 1
+		fi
 	fi
 
 	sh "$BACKUP_INSTALL_DIR/tasks/$SCRIPT_FILE" $ACTION $CUR_TMP_DIR
-	status=$?
+	STATUS=$?
 
-	if [ $status = '0' ]; then
+	if [ $STATUS = '0' ]; then
 		if [ $ACTION = 'dump' ]; then
 			cd $TMP_DIR
-			tar cjvf $BACKUP_ARCHIVE $BACKUP_ID
+			tar cjf $BACKUP_ARCHIVE $BACKUP_ID
+			STATUS=$?
+
+			if [ $STATUS != '0' ]; then
+				echo "  ... failed: Couldn't compress and save backup to $BACKUP_ARCHIVE" 2>&1
+				return 1
+			fi
 		fi
 
 		echo "  ... finished"
+		return 0
 	else
-		scriptError=3
 		echo "  ... $scriptName $ACTION failed" 2>&1
+		return 1
+	fi
+}
+
+echo "$ACTION_LABEL $BACKUP_DIR/*/$BACKUP_ID"
+
+mkdir $TMP_DIR
+
+for SCRIPT_FILE in $(ls "$BACKUP_INSTALL_DIR/tasks" | grep -P "\.sh"); do
+	runBackupTask "$SCRIPT_FILE"
+	STATUS=$?
+
+	if [ $STATUS != '0' ]; then
+		SCRIPT_ERROR=3
 	fi
 
-	rm -rf $CUR_TMP_DIR
+	rm -rf $TMP_DIR/$BACKUP_ID
 done
 
 rm -rf $TMP_DIR
 
-if [ $scriptError = '0' ]; then
+if [ $SCRIPT_ERROR = '0' ]; then
 	echo "Finished successfully"
 else
 	echo "Finished with error(s)"
 fi
 
-exit $scriptError
+exit $SCRIPT_ERROR
