backup finish listeners uniq

diff --git a/cookbooks/algorythm/templates/default/backup.sh.erb b/cookbooks/algorythm/templates/default/backup.sh.erb
--- a/cookbooks/algorythm/templates/default/backup.sh.erb
+++ b/cookbooks/algorythm/templates/default/backup.sh.erb
@@ -133,7 +133,7 @@ function runBackup {
 	LOG_FILE="$LOG_DIR/$ACTION-$BACKUP_DATE.log"
 	TMP_DIR="/tmp/backup-$BACKUP_DATE"
 	TMP_ARCHIVE_DIR="$TMP_DIR/backups"
-	FINISH_SCRIPT_FILE="$TMP_DIR/finish.sh"
+	FINISH_LISTENER_FILE="$TMP_DIR/finish.sh"
 
 	if [ -d "$TMP_DIR" ]; then
 		echo "failed: Temp directory $TMP_DIR is in use" 2>&1
@@ -144,7 +144,7 @@ function runBackup {
 
 	mkdir -p "$BACKUP_DIR"
 	mkdir -p $TMP_ARCHIVE_DIR
-	printf '#!/bin/bash\nEXIT_CODE=0\n' > "$FINISH_SCRIPT_FILE"
+	printf '' > "$FINISH_LISTENER_FILE"
 
 	echo "$ACTION date $BACKUP_DATE:"
 
@@ -211,16 +211,17 @@ function runBackup {
 		cleanDirectory "$LOG_DIR" $MAX_LOGS &>> "$LOG_FILE"
 	fi
 
-	# Run finish script
-	echo 'exit $EXIT_CODE' >> "$FINISH_SCRIPT_FILE"
-	bash "$FINISH_SCRIPT_FILE" &>> "$LOG_FILE"
-	
-	FINISH_SCRIPT_EXIT_CODE=$?
+	# Run finish listeners
+	for FINISH_LISTENER in $(cat "$FINISH_LISTENER_FILE" | sort | uniq); do
+		($FINISH_LISTENER) &>> "$LOG_FILE"
 
-	if [ $FINISH_SCRIPT_EXIT_CODE != '0' ]; then
-		echo '! finish script failed'
-		EXIT_CODE=7
-	fi
+		STATUS=$?;
+
+		if [ $STATUS != '0' ]; then
+			echo 'failed' >> "$LOG_FILE"
+			EXIT_CODE=7
+		fi
+	done
 
 	# Print final status message
 	if [ $EXIT_CODE = '0' ]; then
