backup finish script -> late server restart

diff --git a/cookbooks/algorythm/templates/default/backup-utils.inc.sh.erb b/cookbooks/algorythm/templates/default/backup-utils.inc.sh.erb
--- a/cookbooks/algorythm/templates/default/backup-utils.inc.sh.erb
+++ b/cookbooks/algorythm/templates/default/backup-utils.inc.sh.erb
@@ -25,7 +25,7 @@ function runLaterOnce {
 	STATUS=$?
 
 	if [ $STATUS != '0' ]; then
-		echo "echo '* $LABEL'; $LINE; STATUS=$?; if [ STATUS != '0' ]; then EXIT_CODE=1; fi" >> "$FINISH_SCRIPT_FILE"
+		echo "echo '* $LABEL'; $LINE; STATUS=$?; if [ STATUS != '0' ]; then echo '  failed'; EXIT_CODE=1; fi" >> "$FINISH_SCRIPT_FILE"
 	fi
 }
 
