bash: <&2

diff --git a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
--- a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
+++ b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
@@ -6,7 +6,7 @@
 ### END INIT INFO
 
 if [ $(id -u) != '0' ]; then
-	echo 'You need root privileges to run this script!'
+	echo 'You need root privileges to run this script!' >&2
 	exit 1
 fi
 
@@ -23,17 +23,17 @@ SHUTDOWN_CHECK_INTERVAL=1
 
 id $USER > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-	echo "User '$USER' does not exist!"
+	echo "User '$USER' does not exist!" >&2
 	exit 2
 fi
 
 if [ ! -x "$JAVA_HOME/bin/java" ]; then
-	echo "Java not installed in $JAVA_HOME!"
+	echo "Java not installed in $JAVA_HOME!" >&2
 	exit 2
 fi
 
 if [ ! -f "$JETTY_HOME/start.jar" ] || [ ! -d "$JETTY_HOME/bin" ]; then
-	echo "$APP_NAME Jetty not installed correctly in $JETTY_HOME!"
+	echo "$APP_NAME Jetty not installed correctly in $JETTY_HOME!" >&2
 	exit 2
 fi
 
@@ -44,7 +44,7 @@ function prepareLogFile {
 	LOG_DIR_CREATION_STATUS=$?
 
 	if [ $LOG_DIR_CREATION_STATUS -ne 0 ]; then
-		echo "failed: Cannot write $LOG_DIR!"
+		echo "  failed: Cannot write $LOG_DIR!" >&2
 		exit 2
 	fi
 	
@@ -54,7 +54,7 @@ function prepareLogFile {
 	LOG_FILE_TOUCH_STATUS=$?
 
 	if [ $LOG_FILE_TOUCH_STATUS -ne 0 ]; then
-		echo "failed: Cannot write $LOG_FILE!"
+		echo "  failed: Cannot write $LOG_FILE!" >&2
 		exit 2
 	fi
 }
@@ -66,7 +66,7 @@ function preparePidFile {
 	PID_FILE_TOUCH_STATUS=$?
 
 	if [ $PID_FILE_TOUCH_STATUS -ne 0 ]; then
-		echo "failed: Cannot write PID file $PID_FILE!"
+		echo "  failed: Cannot write PID file $PID_FILE!" >&2
 		exit 2
 	fi
 }
@@ -79,7 +79,7 @@ function start {
 
 	PID=$(cat $PID_FILE) &> /dev/null
 	if [ ! -z $PID ] && [ $(ps -p $PID | grep -c $PID) -ne 0 ]; then
-		echo "failed: $APP_NAME is already running!"
+		echo "  failed: $APP_NAME Jetty is already running!" >&2
 		return 1
 	fi
 
@@ -96,14 +96,16 @@ function stop {
 	preparePidFile
 
 	if [ ! -f $PID_FILE ] || [ ! -s $PID_FILE ]; then
-		printf "\nfailed: not running or invalid PID file $PID_FILE\n"
+		printf '\n'
+		echo "  failed: $APP_NAME Jetty not running or invalid PID file $PID_FILE" >&2
 		return 1
 	fi
 
 	PID=$(cat $PID_FILE)
 
 	if [ $(ps -p $PID | grep -c $PID) -eq 0 ]; then
-		printf "\nInvalid PID. Removing PID file\n"
+		printf '\n'
+		echo "  Invalid PID. Removing PID file $PID_FILE" >&2
 		rm -f $PID_FILE
 		return 1
 	fi
@@ -118,7 +120,8 @@ function stop {
 		WAITED=$(expr $WAITED_TIME + $SHUTDOWN_CHECK_INTERVAL);
 
 		if [ $WAITED_TIME -ge $SHUTDOWN_TIMEOUT ]; then
-			printf "\nSending SIGKILL after $SHUTDOWN_TIMEOUTs timeout"
+			printf '\n'
+			printf "  Sending SIGKILL after $SHUTDOWN_TIMEOUTs timeout " >&2
 			kill -SIGKILL $PID
 			sleep 1
 			echo "=== SENT SIGKILL ===" >> "$LOG_FILE"
@@ -144,7 +147,7 @@ function status {
 }
 
 function showUsageAndExit {
-	echo "Usage: service $APP_NAME {start|stop|restart|status}"
+	echo "Usage: service $APP_NAME {start|stop|restart|status}" >&2
 	exit 1
 }
 
diff --git a/cookbooks/algorythm/templates/default/init.d.liferay.erb b/cookbooks/algorythm/templates/default/init.d.liferay.erb
--- a/cookbooks/algorythm/templates/default/init.d.liferay.erb
+++ b/cookbooks/algorythm/templates/default/init.d.liferay.erb
@@ -25,9 +25,9 @@ SHUTDOWN_TIMEOUT=45
 SHUTDOWN_CHECK_INTERVAL=5
 
 #verify that the user that will run the daemon exists
-id "$USER" > /dev/null 2>&1
+id "$USER" > /dev/null >&2
 if [ $? != '0' ]; then
-	echo "User '$USER' does not exist!" 2>&1
+	echo "User '$USER' does not exist!" >&2
 	exit 1
 fi
 
@@ -44,7 +44,7 @@ function start {
 	status=$?
 
 	if [ $status -ne 0 ]; then
-		echo 'failed' 2>&1
+		echo 'failed' >&2
 	fi
 
 	return $status
@@ -54,14 +54,14 @@ function stop {
 	echo "Stopping $APP_NAME..."
 
 	if [ ! -f $CATALINA_PID ] || [ ! -s $CATALINA_PID ]; then
-		echo "failed: $APP_NAME is not running or pid file $CATALINA_PID is missing or empty!" 2>&1
+		echo "failed: $APP_NAME is not running or pid file $CATALINA_PID is missing or empty!" >&2
 		return 1
 	fi
 
 	pid=$(cat $CATALINA_PID)
 	waited_time=0
 
-	su $USER -c "$CATALINA_HOME/bin/catalina.sh stop" 2>&1 | grep -P '^java\.net\.ConnectException:' &> /dev/null
+	su $USER -c "$CATALINA_HOME/bin/catalina.sh stop" >&2 | grep -P '^java\.net\.ConnectException:' &> /dev/null
 	GREP_ERROR_STATUS=$?
 	
 	if [ $GREP_ERROR_STATUS = '0' ]; then
@@ -77,7 +77,7 @@ function stop {
 	done
 
 	if [ $waited_time -ge $SHUTDOWN_TIMEOUT ]; then
-		echo "Killing process after a timeout of $SHUTDOWN_TIMEOUT seconds"
+		echo "Killing process after a timeout of $SHUTDOWN_TIMEOUT seconds" >&2
 		kill -9 $pid
 		sleep 1
 	fi
@@ -103,7 +103,7 @@ case "$1" in
         $1
     ;;
     *)
-        echo "Usage: service liferay {start|stop|restart|status}"
+        echo "Usage: service liferay {start|stop|restart|status}" >&2
         exit 1
     ;;
 esac
