liferay init.d script

diff --git a/cookbooks/algorythm/templates/default/init.d.liferay.erb b/cookbooks/algorythm/templates/default/init.d.liferay.erb
--- a/cookbooks/algorythm/templates/default/init.d.liferay.erb
+++ b/cookbooks/algorythm/templates/default/init.d.liferay.erb
@@ -9,128 +9,89 @@
 # Default-Stop: 0 1 6
 # Short-Description: Liferay portal daemon.
 # Description: Starts the Liferay portal.
-# Author: Julien Rialland <julien.rialland@gmail.com>
-# Author: Orin Fink <orin.fink@thirdwavellc.com>
 ### END INIT INFO
 
-#Display name of the application
-APP_NAME="Liferay"
-
-#Location of Liferay installation
-export LIFERAY_HOME="<%=@liferayHomeDir%>"
-
-#unprivileged user that runs the daemon.
-USER=<%=@user%>
-
-###This is end of the configurable section for most cases, other variable definitions follow :
-
-#Only root user may run this script
-if [ `id -u` -ne 0 ]; then
-    echo "You need root privileges to run this script"
-    exit 1
+if [ $(id -u) != '0' ]; then
+	echo 'You need root privileges to run this script'
+	exit 1
 fi
 
-#tomcat directory
+APP_NAME="Liferay"
+USER=<%=@user%>
 export CATALINA_HOME="<%=@liferayDir%>"
-
-#location of pid file
 export CATALINA_PID=/var/run/liferay.pid
-
-#extra jvm configuration : enable jmx
-#export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
-
-#extra jvm configuration : enable remote debugging
-#export JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9998"
-
-################################################################################
+export LIFERAY_HOME="<%=@liferayHomeDir%>"
+SHUTDOWN_TIMEOUT=45
+SHUTDOWN_CHECK_INTERVAL=5
 
 #verify that the user that will run the daemon exists
 id "$USER" > /dev/null 2>&1
-if [ "$?" -ne "0" ]; then
-    echo "User $user does not exist !"
-    exit 1
+if [ $? != '0' ]; then
+	echo "User $USER does not exist!" 2>&1
+	exit 1
 fi
 
-#load utility functions from Linux Standard Base
-<% case node['platform_family'] %>
-<% when "debian" %>
-. /lib/lsb/init-functions
-<% when "rhel" %>
-. /etc/init.d/functions
-<% end %>
-
-#starts the daemon service
 function start {
-    <% case node['platform_family'] %>
-    <% when "debian" %>
-        log_daemon_msg "Starting $APP_NAME"
-    <% when "rhel" %>
-        echo "Starting $APP_NAME"
-    <% end %>
+	echo "* Starting $APP_NAME"
 
-        #create work directory if non-existent
-        mkdir $CATALINA_HOME/work 2>/dev/null
+	mkdir $CATALINA_HOME/work 2> /dev/null
+	rm -rf "$CATALINA_HOME/temp/*" 2> /dev/null
+	mkdir $CATALINA_HOME/temp 2> /dev/null
+	touch $CATALINA_PID 2> /dev/null
+	chmod ugo=rw "$CATALINA_PID"
 
-        #clear temp directory
-        rm -rf "$CATALINA_HOME/temp/*" 2>/dev/null
-        mkdir $CATALINA_HOME/temp 2>/dev/null
+	su $USER -c "$CATALINA_HOME/bin/catalina.sh start"
+	status=$?
 
-        #ensure that pid file is writeable
-        touch "$CATALINA_PID" 2>/dev/null
-        chmod ugo=rw "$CATALINA_PID"
+	if [ $status = 0 ]; then
+		echo '  ...ok'
+	else
+		echo '  ...failed' 2>&1
+	fi
 
-        su "$USER" -c "$CATALINA_HOME/bin/catalina.sh start"
-        status=$?
-    
-    <% case node['platform_family'] %>
-    <% when "debian" %>
-        log_end_msg $status
-    <% end %>
-
-        exit $status
+	return $status
 }
 
-#stops the daemon service
 function stop {
-    <% case node['platform_family'] %>
-    <% when "debian" %>
-        echo "Stopping $APP_NAME"
-    <% when "rhel" %>
-        echo "Stopping $APP_NAME"
-    <% end %>
+	echo "* Stopping $APP_NAME"
 
-        if [ ! -f "$CATALINA_PID" ];then
-            echo "file $CATALINA_PID is missing !"
-            unset CATALINA_PID
-        fi
-        su "$USER" -c "$CATALINA_HOME/bin/catalina.sh stop 15"
-        status=$?
+	if [ ! -f $CATALINA_PID ] || [ ! -s $CATALINA_PID ]; then
+		echo "  ...failed: Missing or empty pid file $CATALINA_PID!" 2>&1
+		return 1
+	fi
 
-    <% case node['platform_family'] %>
-    <% when "debian" %>
-        log_end_msg $status
-    <% end %>
+	pid=$(cat $CATALINA_PID)
+	waited_time=0
 
-        rm -f "$CATALINA_PID"
-        exit 0
+	su $USER -c "$CATALINA_HOME/bin/catalina.sh stop"
+
+	until [ $(ps -p $pid | grep -c $pid) = 0 ] || [ $waited_time -ge $SHUTDOWN_TIMEOUT ]; do
+		echo "  ...Waiting for process to exit. Timeout: $waited_time/$SHUTDOWN_TIMEOUT"
+		sleep $SHUTDOWN_CHECK_INTERVAL
+		waited_time=$(expr $waited_time + $SHUTDOWN_CHECK_INTERVAL);
+	done
+
+	if [ $waited_time -ge $SHUTDOWN_TIMEOUT ]; then
+		echo "  ...Killing process after a timeout of $SHUTDOWN_TIMEOUT seconds"
+		kill -9 $pid
+	fi
+
+	rm -f "$CATALINA_PID"
+
+	echo '  ...ok'
+	return 0
 }
 
-#restarts the daemon service
 function restart {
-        stop
-        sleep 3s
-        start
+	stop
+	start
 }
 
-#prints service status
 function status {
   if [ -f "$CATALINA_PID" ]; then
-    pid=`cat "$CATALINA_PID"`
-    echo "$APP_NAME is running with pid $pid"
-    exit 0
+    echo "$APP_NAME is running with pid $(cat $CATALINA_PID)"
   else
     echo "$APP_NAME is not running (or $CATALINA_PID is missing)"
-    exit 1
   fi
 }
 
@@ -139,7 +100,7 @@ case "$1" in
         $1
     ;;
     *)
-        echo $"Usage: $0 {start|stop|restart|status}"
+        echo $"Usage: service liferay {start|stop|restart|status}"
         exit 1
     ;;
 esac
