jetty config

diff --git a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
--- a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
+++ b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
@@ -37,22 +37,23 @@ if [ ! -f "$JETTY_HOME/start.jar" ] || [ ! -d "$JETTY_HOME/bin" ]; then
 	exit 2
 fi
 
-mkdir -p $LOG_DIR
-LOG_DIR_CREATION_STATUS=$?
-
-if [ $LOG_DIR_CREATION_STATUS -ne 0 ]; then
-	echo "Cannot create directory $LOG_DIR!"
-	exit 2
-fi
-
 function prepareLogFile {
-	touch $LOG_FILE &&
-	chown root:$USER $LOG_FILE &&
+	mkdir -p $LOG_DIR &&
+	chown -R root:$USER $LOG_DIR &&
+	chmod 775 $LOG_DIR
+	LOG_DIR_CREATION_STATUS=$?
+
+	if [ $LOG_DIR_CREATION_STATUS -ne 0 ]; then
+		echo "failed: Cannot write $LOG_DIR!"
+		exit 2
+	fi
+	
+	su $USER -c "touch $LOG_FILE" &&
 	chmod 660 $LOG_FILE
 	LOG_FILE_TOUCH_STATUS=$?
 
 	if [ $LOG_FILE_TOUCH_STATUS -ne 0 ]; then
-		echo "failed: Cannot write log file $LOG_FILE!"
+		echo "failed: Cannot write $LOG_FILE!"
 		exit 2
 	fi
 }
