jetty init.d script: ulimit set manually before starting

diff --git a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
--- a/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
+++ b/cookbooks/algorythm/templates/default/init.d.liferay-jetty.erb
@@ -16,7 +16,7 @@ export JETTY_HOME='<%=@installDir%>'
 export JAVA_HOME='/usr/lib/jvm/java-6-openjdk-amd64'
 export JAVA_OPTS='-Dapp.server.jetty.version=8.1.10 -Dapp.server.jetty.version.date=20130312 -Dfile.encoding=UTF8 -Djava.net.preferIPv4Stack=true  -Duser.timezone=Europe/Berlin -Xmx768m -XX:MaxPermSize=256m'
 LOG_DIR=/var/log/jetty
-LOG_FILE="$LOG_DIR/$APP_NAME"
+LOG_FILE="$LOG_DIR/$APP_NAME.log"
 PID_FILE="/var/run/$APP_NAME.pid"
 SHUTDOWN_TIMEOUT=45
 SHUTDOWN_CHECK_INTERVAL=1
@@ -47,8 +47,8 @@ function prepareLogFile {
 		exit 2
 	fi
 	
-	su $USER -c "touch '$LOG_FILE'" &&
-	chown -R root:$USER "$LOG_FILE" &&
+	su $USER -c "touch '$LOG_FILE'" &> /dev/null &&
+	chown root:$USER "$LOG_FILE" &&
 	chmod 660 "$LOG_FILE"
 	LOG_FILE_TOUCH_STATUS=$?
 
@@ -59,13 +59,13 @@ function prepareLogFile {
 }
 
 function preparePidFile {
-	touch $PID_FILE &&
+	touch $PID_FILE &> /dev/null &&
 	chown root:$USER $PID_FILE &&
 	chmod 660 $PID_FILE
 	PID_FILE_TOUCH_STATUS=$?
 
 	if [ $PID_FILE_TOUCH_STATUS -ne 0 ]; then
-		echo "  failed: Cannot write PID file $PID_FILE!" >&2
+		echo "  failed: Cannot write $PID_FILE!" >&2
 		exit 2
 	fi
 }
